# æ ‡ç­¾é¡µå›¾æ ‡
favicon:
  type: "image/x-icon"
  href: "/favicon.ico"

# canvas åŠ¨æ€èƒŒæ™¯
canvas_dust: true

# é»˜è®¤é¢œè‰²æ¨¡å¼ dark / light / auto
# dark æš—è‰²æ¨¡å¼
# light äº®è‰²æ¨¡å¼
# auto è·Ÿéšç³»ç»Ÿ
color: auto

# <body> èƒŒæ™¯å›¾ç‰‡é“¾æ¥
background_image:
  dark: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # æš—è‰²æ¨¡å¼
  light: /img/bk.jpg # äº®è‰²æ¨¡å¼

# å¯¼èˆªæ 
menu:
  Home: ""
  Archives: archives/
  About: about/
  Music: music/

# ä¾§è¾¹æ 
aside:
  in_left: true # ä¾§è¾¹æ åœ¨å·¦ true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png #å›¾ç‰‡é“¾æ¥ï¼Œå»ºè®® 1:1 æ¯”ä¾‹
  dr: / # ä¾§è¾¹æ  Dr. é“¾æ¥
  icp: # ICP å¤‡æ¡ˆå·ï¼Œä¸ç‰ˆæƒå£°æ˜ç›¸åŒï¼Œä½†ä¼šé“¾æ¥åˆ° https://beian.miit.gov.cn/
  copyright: 
    ğŸ§‘ğŸ»â€ğŸ’»:  å°ç‹¼  Syaoran 
    ğŸŒ: 2020-Present
  # ç‰ˆæƒå£°æ˜ã€å¤‡æ¡ˆå·ç­‰ï¼Œå¯è‡ªå®šä¹‰é”®å€¼ï¼Œä¸æƒ³æ˜¾ç¤ºåˆ™ç•™ç©º

# ç¤¾äº¤é“¾æ¥
# æ ¼å¼ï¼šé“¾æ¥ || å›¾æ ‡
social:
  GitHub: https://github.com/Syaoran33 || fab fa-github
  Bilibili: https://space.bilibili.com/276567009 || fab fa-bilibili
  Reddit: https://www.reddit.com/user/Shaoran33 || fab fa-reddit
  # E-Mail: mailto:yourname@gmail.com || fa fa-envelope
  # Weibo: https://weibo.com/yourname || fab fa-weibo
  # Zhihu: https://www.zhihu.com/people/yourname || fab fa-zhihu

# post æ–‡ç« é¡µé¢é…ç½®ï¼›true / false
post:
  date: true # æ˜¯å¦æ˜¾ç¤ºå‘å¸ƒæ—¥æœŸ
  updated: true # æ˜¯å¦æ˜¾ç¤ºä¿®æ”¹æ—¥æœŸ
  excerpt: false # æ˜¯å¦åœ¨æ–‡ç« ä¸­æ˜¾ç¤ºæ‘˜è¦å†…å®¹ï¼ˆ<!-- more--> ä»¥ä¸Šçš„å†…å®¹ï¼‰
  # æ–‡ç« æœ«æ˜¾ç¤ºæ‰“èµäºŒç»´ç 
  reward:
    # æ”¯ä»˜å® | Alipay: img/Alipay.png
    # å¾®ä¿¡ | Wechat: img/WeChat.png
  # ä»¥ä¸‹ä¸¤é¡¹ä¾èµ– hexo-wordcountï¼Œè¯·å‚é˜… README å¼€å¯
  count: true # æ˜¯å¦æ˜¾ç¤ºå­—æ•°ç»Ÿè®¡
  time: true # æ˜¯å¦æ˜¾ç¤ºé¢„è®¡é˜…è¯»æ—¶é•¿

# æ–‡ç« å†…ç›®å½•
toc:
  list_number: true # true / false ï¼›æ˜¯å¦æ˜¾ç¤ºç¼–å·
  max_depth: 6 # æœ€å¤§ç›®å½•æ·±åº¦
  min_depth: 1 # æœ€å°ç›®å½•æ·±åº¦

# å½’æ¡£é¡µ
archives:
  categories_count: true # æ˜¯å¦æ˜¾ç¤ºåˆ†ç±»æ€»æ•°
  tags_count: true # æ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾æ€»æ•°

# æœç´¢
search:
  enable: true
  content: true # è‹¥ä¸º falseï¼Œä»…å¯æœç´¢æ ‡é¢˜åŠ metadata
  preload: false # è‡ªåŠ¨åŠ è½½æœç´¢æ•°æ®
  # è®¾ä¸º post æ—¶ï¼Œä»…å¯æœç´¢ post é¡µé¢
  # è®¾ä¸º page æ—¶ï¼Œä»…å¯æœç´¢é post é¡µé¢
  # è®¾ä¸º all æ—¶ï¼Œå¯æœç´¢å…¨éƒ¨é¡µé¢
  field: post
  # è®¾ä¸º html æ—¶ï¼Œä¾æ® html æ–‡ä»¶ç”Ÿæˆ
  # è®¾ä¸º striptags æ—¶ï¼Œæ»¤é™¤ html tag
  # è®¾ä¸º raw æ—¶ï¼Œä¾æ® markdown æºæ–‡ä»¶ç”Ÿæˆ
  format: striptags

# Valine
# è¯¦è§ https://valine.js.org
valine:
  enable: false
  app_id: # APP ID
  app_key: # APP KEY
  server_url: # APP DOMAINï¼ˆLeanCloud å›½é™…ç‰ˆï¼‰

# gitalk
# è¯¦è§ https://github.com/gitalk/gitalk
gitalk:
  enable: false
  client_id: # GitHub åº”ç”¨ Client ID
  client_secret: # GitHub åº”ç”¨ Client Secret
  repo: # ç”¨äºå­˜æ”¾è¯„è®ºæ•°æ®çš„ GitHub ä»“åº“
  owner: # è¯¥ GitHub ä»“åº“æ‰€æœ‰è€…
  admin: [] # å…·æœ‰å†™è¯¥ GitHub ä»“åº“æƒé™çš„ç”¨æˆ·ï¼Œä¾‹å¦‚: [adminA,adminB]
  id: # (å¯é€‰) é¡µé¢çš„å”¯ä¸€æ ‡è¯†ï¼Œä¾‹å¦‚: location.pathname

# Waline
# è¯¦æƒ…: https://waline.js.org/
waline:
  enable: false
  server_url: #Server_Url

# å›¾è¡¨æ”¯æŒ
mermaid:
  enable: true
  version: "9.2.2"

# pjax æ”¯æŒ
pjax:
  enable: true

# å…¬å¼å‰ç«¯æ¸²æŸ“
mathjax:
  enable: false
  version: "2.6.1"

# åœ¨ `<head>` æ ‡ç­¾å†…å¼•å…¥ CSS æ ·å¼è¡¨
stylesheets:

# åœ¨ `<body>` å°¾éƒ¨å¼•å…¥ JavaScript è„šæœ¬
scripts:
